=== damico/ivela/trunk/ivela-commons/src/main/resources/schema/repository.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.ivela.com/schema/repository"
            xmlns:tns="http://www.ivela.com/schema/repository"
            elementFormDefault="qualified">
    <xsd:complexType name="directory">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="created_by" type="xsd:string"/>
            <xsd:element name="created_at" type="xsd:string"/>
            <xsd:element name="directory" type="tns:directory" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
            <xsd:element name="file" type="tns:file" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>        
    </xsd:complexType>
    <xsd:complexType name="file">
        <xsd:all>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="mimetype" type="xsd:string"/>
        </xsd:all>        
    </xsd:complexType>
    <xsd:element name="repository">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:string"/>
                <xsd:element name="next_value" type="xsd:string"/>
                <xsd:element name="created_at" type="xsd:string"/>
                <xsd:element name="directory" type="tns:directory" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
            </xsd:sequence>            
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== damico/ivela/trunk/ivela-commons/src/main/resources/schema/repository.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : repository.xml
    Created on : June 11, 2008, 4:27 PM
    Author     : marcus
    Description:
        Purpose of the document follows.
-->
<repository  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.ivela.com/schema/repository'
   xsi:schemaLocation='http://www.ivela.com/schema/repository repository.xsd'>
    <id>1</id>
    <next_value>3</next_value>
    <created_at>today</created_at>
    <directory>
        <id>1</id>
        <name>diretorio 1</name>
        <created_by>marcus</created_by>
        <created_at>today</created_at>
        <file>
            <id>1</id>
            <name>arquivo1</name>
            <title>arquivo 1</title>
            <mimetype>text/plain</mimetype>
        </file>
    </directory>
    <directory>
        <id>2</id>
        <name>diretorio 2</name>
        <created_by>marcus</created_by>
        <created_at>today</created_at>
        <file>
            <id>2</id>
            <name>arquivo1</name>
            <title>arquivo 1</title>
            <mimetype>text/plain</mimetype>
        </file>
    </directory>
</repository>
